name: score_io
description: The Generic Domain Language/Library for the Score.io ecosystem.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  uuid: ^2.2.2
  firebase: ^7.3.3
  protobuf: 1.1.0
  protoc_plugin: 19.2.0+1
  jaguar_cqrs: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  ogurets: ^3.2.0
